### ISSUE TITLE
Periodically keep Pubnub connection alive

### ISSUE THREAD

**Issue by jimsmith** [inovex/zax#30]
Hi,

I don't want to burst this bubble - however.......

Leaving the phone after a while pubnub notifications stopped come thru.
I was watching Zabbix dashboard on the phone and noticed a PROBLEM in dashboard but it never came thru to the Zax app.

I sent tests via pubnub dev console and they didn't arrive even via 4G/WiFi

I did however manage to diagnose and replicate this method over 5 times:

UNTICK either of the following:
- Alternative notification icons
- Enabled

then RE-TICK either of the above - then this message is displayed:
'Successfully connected to Pubnub' is displayed 

Then sending a message via pubnub dev console arrives straight away and so does pubnub.pl alerts from Zabbix.

Maybe there should be an option to refresh pubnub in the background to keep the connection to pubnub ?

**Comment by NiciDieNase** [comment]
I did a long-term test (over a few weeks) with the current version and notifications seem to arrive without a problem.
