### ISSUE TITLE
Push (pubnub) notification not working after update to version 2.5

### ISSUE THREAD

**Issue by mishomvp** [inovex/zax#54]
Hello,

Yesterday  update my Zax to version 2.5 and after update push notification doesn't working. 
After update i filled pubnub Subscribe key again, but still doesn't working.
Thanks in advance!

**Comment by NiciDieNase** [comment]
@mishomvp  Did you have the beta-version installed before?

**Comment by mishomvp** [comment]
Hi,
No. Only official version from google play.

**Comment by NiciDieNase** [comment]
A new version is uploaded to play store and should be available soon.

**Comment by mishomvp** [comment]
Thanks! :+1:

**Comment by mishomvp** [comment]
Hi again,

Still not working... I test with Android 4.2.2 and 5.0.2. But i don't receive push notification.
In my pubnub.log i see "Sent", but on phone nothing.
In the previous version i see "Successfully connected to pubnub... " now no.
Any ideas?
Update:
With https://gist.github.com/aikar/e2b58ca22d1c84537111 everything works.

**Comment by fgallese** [comment]
I'm having this exact same issue. Have you found a workaround for this ?

**Comment by mishomvp** [comment]
Just use php script instead perl script :)

**Comment by fgallese** [comment]
I am using it, the issue is not publishing, but the push itself. The app is not connecting to pubnub.

**Comment by mishomvp** [comment]
Do you try to dump communication between phone and pubnub servers? Try to uninstall and install it again? (After uninstall check filesystem for other files from zax ) And then install again :)

**Comment by fgallese** [comment]
Deleting all data and re-installing fixed the problem..
Thank you !

**Comment by fgallese** [comment]
Well.. it stopped working again.

The messages do get published, I can see them with the PubNub debug console. However, the app is not getting them.
